name: bangalore_chakma_society
description: " The Bangalore Chakma Society (BCS) represents the collective journey, 
               resilience, and unity of the Chakma and Buddhist communities who have 
              made Bengaluru their home. The roots of this journey trace back to the 
              early arrivals of Chakma individuals in the city, beginning with pioneers 
              who came as students and professionals and went on to build successful 
              careers laying a proud foundation for the community."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.3.beta
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  file_picker: ^10.3.10
  youtube_player_iframe: ^5.2.2
  web: ^1.1.1
  cloud_functions: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  responsive_builder: ^0.7.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  video_player: ^2.11.0
  chewie: ^1.13.0
  carousel_slider: ^5.1.2
  mailer: ^6.1.0
  http: ^1.2.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
