// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWBSFAMB9N3i23jG3QgVOk-bP2SVbpyxk',
    appId: '1:696836863160:web:491a32e6b832902a6c704d',
    messagingSenderId: '696836863160',
    projectId: 'ngowebsite-6d243',
    authDomain: 'ngowebsite-6d243.firebaseapp.com',
    storageBucket: 'ngowebsite-6d243.firebasestorage.app',
    measurementId: 'G-SV1DW7FNLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_zNaPizoY_p06o9uCAmC6IBEJVqwHlg',
    appId: '1:696836863160:android:0f2ba110049dbae66c704d',
    messagingSenderId: '696836863160',
    projectId: 'ngowebsite-6d243',
    storageBucket: 'ngowebsite-6d243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Oob97-OiDNEh_22daHO2A8asvdgDlOs',
    appId: '1:696836863160:ios:9fa4aa5488c643b16c704d',
    messagingSenderId: '696836863160',
    projectId: 'ngowebsite-6d243',
    storageBucket: 'ngowebsite-6d243.firebasestorage.app',
    iosBundleId: 'com.example.ngoWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Oob97-OiDNEh_22daHO2A8asvdgDlOs',
    appId: '1:696836863160:ios:9fa4aa5488c643b16c704d',
    messagingSenderId: '696836863160',
    projectId: 'ngowebsite-6d243',
    storageBucket: 'ngowebsite-6d243.firebasestorage.app',
    iosBundleId: 'com.example.ngoWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWBSFAMB9N3i23jG3QgVOk-bP2SVbpyxk',
    appId: '1:696836863160:web:e4b652a64da439a46c704d',
    messagingSenderId: '696836863160',
    projectId: 'ngowebsite-6d243',
    authDomain: 'ngowebsite-6d243.firebaseapp.com',
    storageBucket: 'ngowebsite-6d243.firebasestorage.app',
    measurementId: 'G-E4Z5PV6HVQ',
  );
}
